In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# getting started with numpy


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [5]:
import numpy as np
print(np.__version__)

1.18.5


#  create a numpy ndarray object

In [6]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
arr = np.array([345])
print(arr)
print(type(arr))

[345]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(arr)
print(type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
a = np.array(567)
b = np.array([1,2,3,4,5,6,7])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [12]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1])

2


In [13]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[2])

3


In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[3])

4


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1] + arr[2])

5


In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[2] + arr[4])

8


In [17]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd dim: ',c[1,4])

5th element on 2nd dim:  10


In [18]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)
print('5th element on 2nd dim: ',c[1,4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5th element on 2nd dim:  10


In [19]:
import numpy as np
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)
print('print the third element of second array of the first array: ',c[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
print the third element of second array of the first array:  6


In [20]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c)
print('last element on 2nd dim: ',c[1,-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
last element on 2nd dim:  10


In [21]:
import numpy as np
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)
print('print the last element of second array of the second array: ',c[1,1,-1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
print the last element of second array of the second array:  11


In [22]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6])

[2 3 4 5 6]


In [23]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5])

[2 3 4 5]


In [24]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[5:])

[ 6  7  8  9 10]


In [25]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
print(c[7:])

[ 8  9 10 11 12 13 14 15 16 17 18]


In [26]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[:-1])

[1 2 3 4 5 6 7 8 9]


In [27]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-6:-1])

[5 6 7 8 9]


In [28]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-6:0])

[]


In [29]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[5:-3])

[6 7]


In [30]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-3:-1])

[8 9]


In [31]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5:2])

[2 4]


In [32]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5:3])

[2 5]


In [33]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6:3])

[2 5]


In [34]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6:2])

[2 4 6]


In [35]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10])
print(c[::2])

[1 3 5 7 9]


In [36]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
print(c[::2])

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [37]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
print(c[2::])

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [38]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23])
print(c[1::])

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [39]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [40]:
import numpy as np
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c[0:2,1:3])

[[2 3]
 [7 8]]


In [41]:
import numpy as np
c = np.array (['Madhu','Sai','Mansi','Payal','Ashwini','Rahul'])
print(c.dtype)

<U7


In [42]:
import numpy as np
c = np.array([1,2,3,4,5])
print(c.dtype)

int32


In [43]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
newarray = c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4 5]
int32


In [44]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44])
newarray = c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4]
int32


In [45]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
newarray = c.astype(bool)
print(newarray)
print(newarray.dtype)

[ True  True  True  True  True]
bool


In [46]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
newarray = c.astype(int)
print(newarray)
print(c.dtype)

[1 2 3 4 5]
float64


In [47]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
newarray = c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4 5]
int32


In [48]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
x = c.copy()
print(x)
print(c)
print(x.dtype)

[1.23 2.3  3.44 4.44 5.44]
[1.23 2.3  3.44 4.44 5.44]
float64


In [49]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
x = c.view()
x[0] = 34
print(x)
print(c)
print(x.dtype)

[34.    2.3   3.44  4.44  5.44]
[34.    2.3   3.44  4.44  5.44]
float64


In [50]:
import numpy as np
c = np.array([1.23,2.3,3.44,4.44,5.44])
x = c.view()
x[0]
print(x)
print(c)
print(x.dtype)

[1.23 2.3  3.44 4.44 5.44]
[1.23 2.3  3.44 4.44 5.44]
float64


In [51]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
x = c.view()  ## print the value of the base attribute to check if an array owns its data or not
y = c.copy()  
print(x.base)
print(y.base)


[1.23 2.34 3.44 4.44 5.44]
None


In [52]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
y = np.array (['Madhu','Sai','Mansi','Payal','Ashwini','Rahul'])
print(c.shape)
print(y.shape)


(5,)
(6,)


In [53]:
import numpy as np
c = np.array([1.23,2.34,3.44,4.44,5.44])
y = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c.shape)
print(y.shape)


(5,)
(2, 5)


In [54]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = c.reshape(4,3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
import numpy as np
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = c.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [56]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
newarr = arr.reshape(-1)
print(arr)
print(newarr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [57]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.concatenate((arr1,arr2))
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [58]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.stack((arr1,arr2),axis = 1)
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [59]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.stack((arr1,arr2),axis = 0)
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [60]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.hstack((arr1,arr2))
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [61]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.vstack((arr1,arr2))
print(arr1)
print(arr2)
print(newarr)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [62]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
newarr = np.dstack((arr1,arr2))

print(newarr)

[[[1 4]
  [2 5]
  [3 6]]]


# split the given array in 3 parts

In [63]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [64]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,4)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [65]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,5)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [66]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,6)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [67]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,7)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32)]


In [68]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,8)
print(arr)
print(newarr)

[1 2 3 4 5 6]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


In [69]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [70]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,4)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])

[1 2 3]
[4 5 6]
[7 8]
[ 9 10]


In [71]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,5)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])
print(newarr[4])


[1 2]
[3 4]
[5 6]
[7 8]
[ 9 10]


In [72]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
newarr = np.array_split(arr,6)

print(newarr[0])
print(newarr[1])
print(newarr[2])
print(newarr[3])
print(newarr[4])
print(newarr[5])


[1 2]
[3 4]
[5 6]
[7 8]
[9]
[10]


In [73]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
newarr = np.where(arr==3)

print(newarr)


(array([2], dtype=int64),)


In [74]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
newarr = np.where(arr==4)

print(newarr)


(array([3, 5, 6], dtype=int64),)


In [75]:
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
newarr = np.where(arr==1)

print(newarr)


(array([0], dtype=int64),)


In [76]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.where(arr%2 == 0)

print(newarr)


(array([1, 3, 5, 7], dtype=int64),)


In [77]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.where(arr%2 != 0)

print(newarr)

(array([0, 2, 4, 6], dtype=int64),)


In [78]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
newarr = np.where(arr%2 == 1)

print(newarr)

(array([0, 2, 4, 6], dtype=int64),)


In [79]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7)

print(x)

1


In [80]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,7, side ='right')

print(x)

2


In [81]:
import numpy as np
arr = np.array([6,7,8,9])
x = np.searchsorted(arr,8, side = 'right')

print(x)

3


In [82]:
import numpy as np
arr = np.array([6,8,7,9])
x = np.searchsorted(arr,7, side = 'right')

print(x)

3


In [83]:
import numpy as np
arr = np.array([414,42,43,44])
x = arr[[True,False,True,False]]

print(x)

[414  43]


In [84]:
import numpy as np
arr = np.array([414,42,43,44])
x = arr[[True,True,True,False]]

print(x)

[414  42  43]


In [85]:
import numpy as np
arr = np.array([4,5,6,7])
x = arr[[False,False,True,True]]

print(x)

[6 7]


In [86]:
import numpy as np

arr = np.array([41,42,43,44])

filter_arr = arr>42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [87]:
import numpy as np

arr = np.array([41,42,43,44,45,46,47,48,49])

filter_arr = arr>42 

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True  True  True  True  True  True]
[43 44 45 46 47 48 49]


In [88]:
import numpy as np

arr = np.array([41,42,43,44,45,46,47,48,49,50])

filter_arr = arr>42 

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True  True  True  True  True  True  True]
[43 44 45 46 47 48 49 50]
